services:

  Bo\SecurityNewsWidget\:
    resource: '../Classes/*'

  t3securityNews:
    class: Bo\SecurityNewsWidget\Widgets\T3SecurityNewsWidget
    arguments: ['t3securityNews']
    tags:
      - name: dashboard.widget
        widgetGroups: 'custom'
