services:

  Bo\SecurityNewsWidget\:
    resource: '../Classes/*'

  Bo\SecurityNewsWidget\Widgets\T3SecurityNewsWidget:
    arguments: ['t3securityNews']
    tags:
      - name: dashboard.widget
        identifier: t3securityNews
        widgetGroups: 'custom'
